#!/bin/bash


# Set the GTK theme to the dark variant
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

# Set media to never run automatically
gsettings set org.gnome.desktop.media-handling autorun-never 'true'

# Disable Usage & History
gsettings set org.gnome.desktop.privacy remember-recent-files 'false'

# Set the header bar button layout
gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'

# Show the battery percentage in the panel
gsettings set org.gnome.desktop.interface show-battery-percentage 'true'

# Center new windows
gsettings set org.gnome.mutter center-new-windows 'true'

# Set desktop background
gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/desktop-base/spacefun-theme/wallpaper/gnome-background.xml'

# Show option to permanently delete files in Nautilus
gsettings set org.gnome.nautilus.preferences show-delete-permanently true

# Place app menus back in window title bar
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides '@a{sv} {"Gtk/ShellShowsAppMenu":<0>}'

# Set favorite apps
gsettings set org.gnome.shell favorite-apps "['tor-browser.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'thunderbird.desktop', 'libreoffice-startcenter.desktop', 'org.keepassxc.KeePassXC.desktop']"

# Set enabled extensions
gsettings set org.gnome.shell enabled-extensions "['places-menu@gnome-shell-extensions.gcampax.github.com', 'TopIcons@phocean.net', 'status-menu-helper@tails.boum.org', 'torstatus@tails.boum.org']"

# Notify everything should be configured
notify-send -a wget -u normal "All set captain!"
